apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgBupRYgWeKcBaP6UhvqEgpxVQlUfjs4jeMwrjUGgpnJ8BL6RTAFRt4xjV3aml77cRAHguiaOOTx5IfK7G7l3ehHWYHEkLvsnXaypfWtwULmF7lLWNNfa79B1H1aK/JMvHj9f9VOeXKkGHErhRfuvrfQ1bAjoOovaYlIlCxrYxp35ukcIeNWlAw8ajFRo06mlZwgQMw/ECWvSokJXPf/qAEfooKa8RkvV+4i4KGEnIh/4acbS3+gG363E3PTKBRBXQxwncWmY/fRLoCzYoivx9fhZtC2xG6cEhrpbVLCGFathrqNd8duDdkhVRFM+kFiXOx4m9GQJHhgJT2U33s/5yyiRIeYQCYbiKnAgdCbzWNnn4MPVRwCSnS+9E4+R9MoWu6S7QmgqFARst/TicumrCo215hvipFANwP4J4v9l6IL4tIUHPV4R6rvtcrcwrF7KT0nwKZ7BMbvmMDFnz84TO5P/5JSfLnBAvC5uP+VnzM9pOSdJHr2iZySINu8CRz3lnTgPaZsEYJUMP+DEQQvDmylORo9jcUCudy/hd8SxypvxvmUJscFkjf2M+YOo3rIJnerbnZuJR+gQkxS2Qc7ChGDMw8TL78WSXDYmNzi9y1JL6imBTM4kpJohlEbZDUku/RarQN/4feJlwZODLbYxd3lkx13c/rgnrU04DzwYKuj8mujZOOPLum0HCdw79z3tIyHBOxiV1w1ng==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

